### ISSUE TITLE
src_presto does not work with trino

### ISSUE THREAD

**Issue by ADraginda** [prestodb/RPresto#149] opened 2022-03-24 22:42 UTC
This works:

```R
con <- dbConnect(
  RPresto::Presto(),
  use.trino.headers=TRUE,
  ...
)
```

This fails

```R
RPresto::src_presto(
  use.trino.headers=TRUE,
  ...
)
```

with

```
Error: lexical error: invalid char in json text.
                                       java.lang.IllegalArgumentExcept
                     (right here) ------^
```

And I think that it is because in #147 the arg was not added to `src_presto`?

The docs suggest that either should work, at least as I interpreted 

> To connect to Trino you must set the use.trino.headers parameter so RPresto knows to send the correct headers to the server. Otherwise all the same functionality is supported.

**Comment by leepface** [comment] 2022-07-04 11:29
@ADraginda  Are you able to send a PR to fix?

**Comment by jarodmeng** [comment] 2022-08-20 03:00
@ADraginda I can't reproduce the error. Both dbConnect() and src_presto() work fine with the use.trino.headers parameter on my machine. Can you provide a reprex for us to further troubleshoot here?

**Comment by jarodmeng** [comment] 2022-08-29 08:35
Closing for now as I can't reproduce the error. Please reopen if there's a reproducible example to troubleshoot.

**Closed** 2022-08-29 08:36 UTC
Labels: bug
