### ISSUE TITLE
old dbplyr interface

### ISSUE THREAD

**Issue by copernican** [prestodb/RPresto#150] opened 2022-06-27 14:22 UTC
It appears that RPresto may be using an older dbplyr interface. Pseudocode to reproduce the warning:

```r
library(dplyr)
library(RPresto)

conn <- dbConnect(
  Presto(),
  # other arguments to create connection
)

my_tbl <- tbl(conn, "my_tbl")
```

results in

```
Warning message:
<PrestoConnection> uses an old dbplyr interface
ℹ Please install a newer version of the package or contact the maintainer
This warning is displayed once every 8 hours. 
```

I think this may be related to the [dbplyr 2.0.0 API](https://dbplyr.tidyverse.org/articles/backend-2.html). For example, it appears that `dplyr::db_query_fields()` is currently in use, but will be replaced by a dbplyr generic. I'm using RPresto 1.3.7 and dbplyr 2.2.0.

**Comment by jarodmeng** [comment] 2022-08-19 16:40
This is caused by dbplyr 1.0.0 API entering its sunsetting phase. We need to migrate the dbplyr API usage to dbplyr 2.0.0 (see https://dbplyr.tidyverse.org/articles/backend-2.html).

**Comment by leepface** [comment] 2022-08-24 08:32
Resolved by linked PR

**Closed by leepface** 2022-08-24 08:32 UTC
Labels: bug
